### ISSUE TITLE
Filter with single arguments are not supported

### ISSUE THREAD

**Issue by nikpanos** [nikpanos/DRDF_Query#10]
Filter sections in SPARQL queries, which have a single argument input, throw an OutOfRangeException.

Such examples are included in the TestFilter1 class.

**Comment by nkoutroumanis** [comment]
Single Arguments of Filter Operators are now supported

**Comment by nikpanos** [comment]
This is not resolved yet. It does not throw an Exception now, but also, it does not work as expected.
When a single parameter "?x" is given as input to a filter, it should create a single ColumnOperand. However, currently the code creates an empty ValueOperand.

**Comment by nkoutroumanis** [comment]
fixed
